name: Hanastagram Deployment
run-name: ${{ github.actor }} 의 Hanastagram 배포

on:
  push:
    branches:
      - main
    paths:
      - "apps/hanastagram/**"
      - ".github/workflows/hanastagram.yml"
  pull_request:
    branches:
      - main
    paths:
      - "apps/hanastagram/**"
      - ".github/workflows/hanastagram.yml"
  release:
    types: [created]

jobs:
  hanastagram:
    runs-on: ubuntu-latest
    outputs:
      status: ${{ job.status}}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Use Node.js version 20.x
        uses: actions/setup-node@v3
        with:
          node-version: "20.x"
          cache: "yarn"
          cache-dependency-path: "yarn.lock"

      - name: Install dependencies
        run: yarn install

  amplify-webhook:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: curl -X POST -d {} "https://webhooks.amplify.us-east-2.amazonaws.com/prod/webhooks?id=c47256bb-20c5-48d4-b7a0-60f253103c60&token=lCavAgV4PBdM3hNYQaYZlsoXj0KOeeDcH6ZLbus1eIU&operation=startbuild" -H "Content-Type:application/json"
